pipeline {
  agent any

  environment {
    APP_DIR = "Jenkins-Zero-To-Hero-main1/java-maven-sonar-argocd-helm-k8s/spring-boot-app"
    DOCKER_IMAGE = "induja1408/portfolio-app:${BUILD_NUMBER}"
    SONARQUBE_SERVER = "sonarqube-server"
    NEXUS_REPO_URL = "http://18.234.42.66:8081/repository/maven-releases/"
  }

  stages {

    stage('Checkout Code') {
      steps {
        git branch: 'main', url: 'https://github.com/Induja1408/portfolio-project.git'
      }
    }

    stage('Build & Test') {
      steps {
        dir("${APP_DIR}") {
          sh "mvn clean test"
        }
      }
    }

    stage('SonarQube Analysis') {
      environment {
        SONAR_TOKEN = credentials('sonarqube-token')
      }
      steps {
        dir("${APP_DIR}") {
          withSonarQubeEnv("${SONARQUBE_SERVER}") {
             sh """
               mvn sonar:sonar \
               -Dsonar.projectKey=portfolio-app \
               -Dsonar.host.url=http://18.234.42.66:9000 \
               -Dsonar.login=$SONAR_TOKEN
             """
          }
        }
      }
    }

    stage('Build JAR for Nexus & Docker') {
      steps {
        dir("${APP_DIR}") {
          sh "mvn -DskipTests package"
        }
      }
    }

    stage('Upload JAR to Nexus') {
      environment {
        NEXUS = credentials('nexus-cred')
      }
      steps {
        dir("${APP_DIR}") {
          sh """
            mvn deploy \
            -DaltDeploymentRepository=nexus::default::${NEXUS_REPO_URL} \
            -DrepositoryId=nexus \
            -Dusername=$NEXUS_USR \
            -Dpassword=$NEXUS_PSW
          """
        }
      }
    }

    stage('Build Docker Image') {
      steps {
        dir("${APP_DIR}") {
          sh "docker build -t ${DOCKER_IMAGE} ."
        }
      }
    }

    stage('Push Docker Image to DockerHub') {
      steps {
        withCredentials([usernamePassword(credentialsId: 'docker-cred', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
          sh "echo $PASS | docker login -u $USER --password-stdin"
          sh "docker push ${DOCKER_IMAGE}"
        }
      }
    }

    stage('Deploy Container') {
      steps {
        sh "docker rm -f portfolio-app || true"
        sh "docker run -d -p 8000:8080 --name portfolio-app ${DOCKER_IMAGE}"
      }
    }
  }
}
